# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BranchAndBoundCpp <- function(x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, maxsize, pen, display_progress, NumBest, cutoff) {
    .Call(`_BranchGLM_BranchAndBoundCpp`, x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, maxsize, pen, display_progress, NumBest, cutoff)
}

BackwardBranchAndBoundCpp <- function(x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, pen, display_progress, NumBest, cutoff) {
    .Call(`_BranchGLM_BackwardBranchAndBoundCpp`, x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, pen, display_progress, NumBest, cutoff)
}

SwitchBranchAndBoundCpp <- function(x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, pen, display_progress, NumBest, cutoff) {
    .Call(`_BranchGLM_SwitchBranchAndBoundCpp`, x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, pen, display_progress, NumBest, cutoff)
}

BranchGLMfit <- function(x, y, offset, init, method, m, Link, Dist, nthreads, tol, maxit, GetInit) {
    .Call(`_BranchGLM_BranchGLMfit`, x, y, offset, init, method, m, Link, Dist, nthreads, tol, maxit, GetInit)
}

RLogLik <- function(x, y, offset, beta, Dist, Link) {
    .Call(`_BranchGLM_RLogLik`, x, y, offset, beta, Dist, Link)
}

MetricIntervalCpp <- function(x, y, offset, indices, num, models, method, m, Link, Dist, nthreads, tol, maxit, pen, mle, se, best, cutoff, metrics, rootMethod) {
    .Call(`_BranchGLM_MetricIntervalCpp`, x, y, offset, indices, num, models, method, m, Link, Dist, nthreads, tol, maxit, pen, mle, se, best, cutoff, metrics, rootMethod)
}

ForwardCpp <- function(x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, pen) {
    .Call(`_BranchGLM_ForwardCpp`, x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, pen)
}

BackwardCpp <- function(x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, pen) {
    .Call(`_BranchGLM_BackwardCpp`, x, y, offset, indices, num, interactions, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, pen)
}

MakeTable <- function(preds, y, cutoff) {
    .Call(`_BranchGLM_MakeTable`, preds, y, cutoff)
}

MakeTableFactor2 <- function(preds, y, levels, cutoff) {
    .Call(`_BranchGLM_MakeTableFactor2`, preds, y, levels, cutoff)
}

CindexCpp <- function(preds, y) {
    .Call(`_BranchGLM_CindexCpp`, preds, y)
}

CindexTrap <- function(Sens, Spec) {
    .Call(`_BranchGLM_CindexTrap`, Sens, Spec)
}

ROCCpp <- function(preds, y, Cutoffs) {
    .Call(`_BranchGLM_ROCCpp`, preds, y, Cutoffs)
}

