# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BranchGLMfit <- function(x, y, offset, method, m, Link, Dist, nthreads, tol, maxit) {
    .Call(`_BranchGLM_BranchGLMfit`, x, y, offset, method, m, Link, Dist, nthreads, tol, maxit)
}

ParBranchAndBoundCpp <- function(x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, maxsize, metric, display_progress) {
    .Call(`_BranchGLM_ParBranchAndBoundCpp`, x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, maxsize, metric, display_progress)
}

MakeTable <- function(preds, y, cutoff) {
    .Call(`_BranchGLM_MakeTable`, preds, y, cutoff)
}

MakeTableFactor2 <- function(preds, y, levels, cutoff) {
    .Call(`_BranchGLM_MakeTableFactor2`, preds, y, levels, cutoff)
}

CindexCpp <- function(preds, y) {
    .Call(`_BranchGLM_CindexCpp`, preds, y)
}

CindexTrap <- function(Sens, Spec) {
    .Call(`_BranchGLM_CindexTrap`, Sens, Spec)
}

ROCCpp <- function(preds, y, Cutoffs) {
    .Call(`_BranchGLM_ROCCpp`, preds, y, Cutoffs)
}

GetNum <- function(size, max) {
    .Call(`_BranchGLM_GetNum`, size, max)
}

ForwardCpp <- function(x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, metric) {
    .Call(`_BranchGLM_ForwardCpp`, x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, metric)
}

BackwardCpp <- function(x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, metric) {
    .Call(`_BranchGLM_BackwardCpp`, x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, steps, metric)
}

BranchAndBoundCpp <- function(x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, maxsize, metric, display_progress) {
    .Call(`_BranchGLM_BranchAndBoundCpp`, x, y, offset, indices, num, method, m, Link, Dist, nthreads, tol, maxit, keep, maxsize, metric, display_progress)
}

